[package]
name = "opengamesir"
version = "0.1.0"
edition = "2024"

[dependencies]
array_builder = "0.1.4"
byteorder = "1.5.0"
clap = { version = "4.5.54", features = ["derive"] }
color-eyre = "0.6.5"
eyre = "0.6.12"
hidapi = "2.6.4"
